id: AE864C4A0
title: A Prayer to Yumka Tsogyal
type: translation
pechas:
- I39F54F46
- IB3141C1E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:46.997015
  last_modified_at: 2023-01-04 11:29:46.997026
  collections:
  - Apang Tertön Series
  - Works of Tibetan Masters
alignment_to_base:
  I39F54F46/B074: 95A3
  IB3141C1E/B561: 95A3
